name: Build GWorkspace with GNUstep and Clang

on: [push, pull_request]

env:
  CC: clang
  CXX: clang++
  OBJC: clang

jobs:
  build-gworkspace:
    runs-on: ubuntu-22.04

    steps:
    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          clang \
          gnustep-devel \
          gnustep-make \
          libgnustep-gui-dev \
          libgnustep-base-dev \
          libffi-dev \
          libxml2-dev \
          libtiff-dev \
          libpng-dev \
          libjpeg-dev \
          zlib1g-dev \
          libinotifytools0-dev

    - name: Checkout GWorkspace repository
      uses: actions/checkout@v4

    - name: Configure and build GWorkspace
      run: |
        . /usr/share/GNUstep/Makefiles/GNUstep.sh
        ./configure --with-inotify
        make
        sudo make install

    - name: Build and install GWMetadata
      run: |
        . /usr/share/GNUstep/Makefiles/GNUstep.sh
        cd GWMetadata
        ./configure
        make
        sudo make install

    - name: Zip GWorkspace.app
      run: |
        cd GWorkspace
        zip -r ../GWorkspace.app.zip GWorkspace.app

    - name: Upload GWorkspace.app.zip as artifact
      uses: actions/upload-artifact@v4
      with:
        name: GWorkspace.app
        path: GWorkspace.app.zip
