name: Build GWorkspace with GNUstep and Clang

on: [push, pull_request]

jobs:
  build-gworkspace:
    runs-on: ubuntu-latest

    steps:
    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          clang \
          gnustep-devel \
          gnustep-make \
          build-essential \
          libgnustep-gui-dev \
          libgnustep-base-dev \
          git \
          subversion \
          libffi-dev \
          libxml2-dev \
          libtiff-dev \
          libpng-dev \
          libjpeg-dev \
          zlib1g-dev \
          libinotifytools0-dev \
          libpoppler-dev \
          curl \
          zip

    - name: Checkout GWorkspace repository
      uses: actions/checkout@v4

    - name: Set GNUstep environment and compiler
      run: |
        echo "CC=clang" >> $GITHUB_ENV
        echo "CXX=clang++" >> $GITHUB_ENV
        echo ". /usr/lib/GNUstep/System/Library/Makefiles/GNUstep.sh" >> $GITHUB_ENV

    - name: Configure and build GWorkspace
      run: |
        . /usr/lib/GNUstep/System/Library/Makefiles/GNUstep.sh
        ./configure --with-inotify CC=clang CXX=clang++
        gmake
        sudo gmake install

    - name: Build and install GWMetadata
      run: |
        . /usr/lib/GNUstep/System/Library/Makefiles/GNUstep.sh
        cd GWMetadata
        ./configure CC=clang CXX=clang++
        gmake
        sudo gmake install


    - name: Zip GWorkspace.app
      run: |
        cd GWorkspace
        zip -r ../GWorkspace.app.zip GWorkspace.app

    - name: Upload GWorkspace.app.zip as artifact
      uses: actions/upload-artifact@v4
      with:
        name: GWorkspace.app
        path: GWorkspace.app.zip
